<?php
/** @var \Klump\Payment\Block\System\Config\Fieldset\AdPreview $block */
if ($block->isActive()): ?>
    <div class="klump-product-button" style="margin-top: 15px;">
        <div id="klump__ad">
            <input type="hidden" value="<?= $block->escapeHtmlAttr($block->getProductPrice()) ?>" id="klump__price">
            <input type="hidden" value="<?= $block->escapeHtmlAttr($block->getPublicKey()) ?>" id="klump__merchant__public__key">
            <input type="hidden" value="<?= $block->escapeHtmlAttr($block->getCurrentCurrency()) ?>" id="klump__currency">
        </div>
    </div>
<?php endif; ?>
